services:
  new-api:
    image: codming/new-api:v0.9.0
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - PORT=3000
      - SQL_DSN=postgres://new-api:123456@postgres:5432/new-api?sslmode=disable
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
      - STREAMING_TIMEOUT=600
      - CRYPTO_SECRET=your_crypto_secret
      - FRONTEND_BASE_URL=https://your-domain.com
      - ENFORCE_INCLUDE_USAGE=true

    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: new-api
      POSTGRES_USER: new-api
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"  # If you want to access PostgreSQL from outside Docker, uncomment

volumes:
  postgres_data: