name: Build Custom New API Docker Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build from upstream"
        required: true

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: codming/new-api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up environment
        run: |
          echo "Building custom New API with tag: ${{ github.event.inputs.tag }}"

      - name: Checkout upstream New API repository
        uses: actions/checkout@v4
        with:
          repository: 'QuantumNous/new-api'
          ref: ${{ github.event.inputs.tag }}
          path: 'upstream'

      - name: Checkout override dockerfile
        uses: actions/checkout@v4
        with:
          path: 'overrides'

      - name: Apply override files
        run: |
          cp overrides/Dockerfile upstream/Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}-${{ matrix.arch_suffix }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./upstream
          file: ./upstream/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-${{ matrix.arch_suffix }}:${{ github.event.inputs.tag }}
            ${{ env.IMAGE_PREFIX }}-${{ matrix.arch_suffix }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/s390x
          cache-from: type=gha
          cache-to: type=gha,mode=max
